output "spring_cloud_service_name" {
  value       = local.spring_cloud_service_name
  description = "Azure Spring Cloud service name"
}

output "application_url" {
  value = azurerm_spring_cloud_app.application.url
}

output "application_name" {
  value       = local.spring_cloud_app_name
  description = "The application name generated by the Azure Cloud Adoption Framework."
}

output "mysql_application_username" {
  value       = local.spring_cloud_app_name
  description = "The application user name."
  
}
# important: mysql aad authentication expect the application_id, not the object id. that is the reason to look for the application_id in aad
output "application_identity" {
  value = data.azuread_service_principal.aad_appid.application_id
}
